# Generated by Django 4.0 on 2022-01-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_note_id_alter_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(default='', max_length=25),
        ),
    ]
